name: build backend

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: dotnet install 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - run: docker build
        working-directory: VsModDb
